import type { Metadata } from "next";

const BASE_URL = "https://ruvicode.com";

// Default brand Open Graph image (generated by scripts/gen-og.py).
const OG_IMAGE_BASE = `${BASE_URL}/og`;
const OG_IMAGE_DEFAULT = `${OG_IMAGE_BASE}/ruvicode-default.png`;

interface CreateMetadataOptions {
  title: string;
  description: string; // keep 120-160 chars
  path?: string;
  ogImage?: string; // absolute URL; falls back to the brand default
  noIndex?: boolean;
}

/**
 * Shared metadata template (ADR-011 §8, extended per ADR-029).
 * Ensures every page has consistent canonical, OG, Twitter, and robots tags.
 * Use this for any new page instead of writing raw Metadata objects.
 */
export function createMetadata(opts: CreateMetadataOptions): Metadata {
  const url = opts.path ? `${BASE_URL}${opts.path}` : BASE_URL;
  const image = opts.ogImage ?? OG_IMAGE_DEFAULT;

  return {
    title: opts.title,
    description: opts.description,
    alternates: { canonical: url },
    robots: opts.noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: { index: true, follow: true, "max-image-preview": "large" },
        },
    openGraph: {
      title: opts.title,
      description: opts.description,
      url,
      siteName: "Ruvicode",
      type: "website",
      images: [{ url: image, width: 1200, height: 630, alt: opts.title }],
    },
    twitter: {
      card: "summary_large_image",
      title: opts.title,
      description: opts.description,
      images: [image],
    },
  };
}
