/**
 * Model pricing data — static seed data for local development.
 *
 * This mirrors the `model_prices` table schema (DESIGN.md §12) and will be
 * replaced by Drizzle ORM queries once Postgres is provisioned.
 * The query interface in `src/lib/db/queries/models.ts` stays identical so
 * the swap is a one-file change.
 *
 * Pricing data sourced from PROJECT.md §6 verified margin table.
 */

export interface ModelPricing {
  model: string;
  display_name: string;
  provider: string;
  ref_input: number; // OpenRouter reference $/1M input
  ref_output: number; // OpenRouter reference $/1M output
  user_input: number; // Ruvicode user $/1M input
  user_output: number; // Ruvicode user $/1M output
  discount_pct: number; // Provider discount %
  user_discount_pct: number; // User discount % (provider - 20pp)
  context: string; // Context window
  capabilities: string[]; // e.g. ["text", "vision", "tools", "reasoning"]
  is_active: boolean;
}

export const MODEL_PRICES: readonly ModelPricing[] = [
  {
    model: "claude-opus-4.7",
    display_name: "Claude Opus 4.7",
    provider: "Anthropic",
    ref_input: 5.0,
    ref_output: 25.0,
    user_input: 3.95,
    user_output: 19.75,
    discount_pct: 41.0,
    user_discount_pct: 21.0,
    context: "200K",
    capabilities: ["text", "vision", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "claude-sonnet-5",
    display_name: "Claude Sonnet 5",
    provider: "Anthropic",
    ref_input: 2.0,
    ref_output: 10.0,
    user_input: 1.7,
    user_output: 8.5,
    discount_pct: 35.0,
    user_discount_pct: 15.0,
    context: "200K",
    capabilities: ["text", "vision", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "claude-sonnet-4.6",
    display_name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    ref_input: 3.0,
    ref_output: 15.0,
    user_input: 2.05,
    user_output: 10.25,
    discount_pct: 51.7,
    user_discount_pct: 31.7,
    context: "200K",
    capabilities: ["text", "vision", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "gpt-5.6-sol",
    display_name: "GPT-5.6-Sol",
    provider: "OpenAI",
    ref_input: 5.0,
    ref_output: 20.0,
    user_input: 1.15,
    user_output: 4.6,
    discount_pct: 97.0,
    user_discount_pct: 77.0,
    context: "128K",
    capabilities: ["text", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "gpt-5.4",
    display_name: "GPT-5.4",
    provider: "OpenAI",
    ref_input: 2.5,
    ref_output: 10.0,
    user_input: 1.0,
    user_output: 4.0,
    discount_pct: 80.0,
    user_discount_pct: 60.0,
    context: "128K",
    capabilities: ["text", "vision", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "gpt-5.4-mini",
    display_name: "GPT-5.4 Mini",
    provider: "OpenAI",
    ref_input: 0.75,
    ref_output: 3.0,
    user_input: 0.315,
    user_output: 1.26,
    discount_pct: 78.0,
    user_discount_pct: 58.0,
    context: "128K",
    capabilities: ["text", "vision", "tools"],
    is_active: true,
  },
  {
    model: "gpt-5.5",
    display_name: "GPT-5.5",
    provider: "OpenAI",
    ref_input: 5.0,
    ref_output: 20.0,
    user_input: 1.05,
    user_output: 4.2,
    discount_pct: 99.0,
    user_discount_pct: 79.0,
    context: "128K",
    capabilities: ["text", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "gpt-4o",
    display_name: "GPT-4o",
    provider: "OpenAI",
    ref_input: 2.5,
    ref_output: 10.0,
    user_input: 1.125,
    user_output: 4.5,
    discount_pct: 75.0,
    user_discount_pct: 55.0,
    context: "128K",
    capabilities: ["text", "vision", "tools"],
    is_active: true,
  },
  {
    model: "gemini-3.1-pro",
    display_name: "Gemini 3.1 Pro",
    provider: "Google",
    ref_input: 2.0,
    ref_output: 8.0,
    user_input: 1.39,
    user_output: 5.56,
    discount_pct: 50.5,
    user_discount_pct: 30.5,
    context: "1M",
    capabilities: ["text", "vision", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "gemini-3-flash",
    display_name: "Gemini 3 Flash",
    provider: "Google",
    ref_input: 0.5,
    ref_output: 2.0,
    user_input: 0.35,
    user_output: 1.4,
    discount_pct: 50.0,
    user_discount_pct: 30.0,
    context: "1M",
    capabilities: ["text", "vision", "tools"],
    is_active: true,
  },
  {
    model: "glm-5.2",
    display_name: "GLM-5.2",
    provider: "Zhipu",
    ref_input: 0.95,
    ref_output: 3.8,
    user_input: 0.218,
    user_output: 0.872,
    discount_pct: 97.0,
    user_discount_pct: 77.0,
    context: "128K",
    capabilities: ["text", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "kimi-k3",
    display_name: "Kimi K3",
    provider: "Moonshot",
    ref_input: 3.0,
    ref_output: 12.0,
    user_input: 2.05,
    user_output: 8.2,
    discount_pct: 51.7,
    user_discount_pct: 31.7,
    context: "256K",
    capabilities: ["text", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "kimi-k2.5",
    display_name: "Kimi K2.5",
    provider: "Moonshot",
    ref_input: 0.375,
    ref_output: 1.5,
    user_input: 0.222,
    user_output: 0.888,
    discount_pct: 60.8,
    user_discount_pct: 40.8,
    context: "256K",
    capabilities: ["text", "tools"],
    is_active: true,
  },
  {
    model: "deepseek-v4-flash",
    display_name: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    ref_input: 0.09,
    ref_output: 0.36,
    user_input: 0.027,
    user_output: 0.108,
    discount_pct: 90.0,
    user_discount_pct: 70.0,
    context: "64K",
    capabilities: ["text", "reasoning"],
    is_active: true,
  },
  {
    model: "deepseek-v4-pro",
    display_name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    ref_input: 0.435,
    ref_output: 1.74,
    user_input: 0.13,
    user_output: 0.52,
    discount_pct: 90.1,
    user_discount_pct: 70.1,
    context: "64K",
    capabilities: ["text", "reasoning"],
    is_active: true,
  },
  {
    model: "grok-4.5",
    display_name: "Grok 4.5",
    provider: "xAI",
    ref_input: 2.0,
    ref_output: 8.0,
    user_input: 1.6,
    user_output: 6.4,
    discount_pct: 40.0,
    user_discount_pct: 20.0,
    context: "128K",
    capabilities: ["text", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "qwen-3-max",
    display_name: "Qwen 3 Max",
    provider: "Alibaba",
    ref_input: 1.6,
    ref_output: 6.4,
    user_input: 0.8,
    user_output: 3.2,
    discount_pct: 70.0,
    user_discount_pct: 50.0,
    context: "128K",
    capabilities: ["text", "tools", "reasoning"],
    is_active: true,
  },
  {
    model: "qwen-3-coder",
    display_name: "Qwen 3 Coder",
    provider: "Alibaba",
    ref_input: 0.7,
    ref_output: 2.8,
    user_input: 0.35,
    user_output: 1.4,
    discount_pct: 65.0,
    user_discount_pct: 45.0,
    context: "256K",
    capabilities: ["text", "tools"],
    is_active: true,
  },
] as const;
