import { getSession } from "@/lib/session";
import { notFound } from "next/navigation";
import { getAdminTools } from "@/lib/db/queries/admin-tools";
import { listAdminAudit } from "@/lib/db/queries/admin-audit";
import { SweepPanel } from "@/components/admin/sweep-panel";
import { ClientTime } from "@/components/shared/client-time";
export const dynamic = "force-dynamic";
function ok(email: string | null | undefined) { return !!email && (process.env.ADMIN_EMAILS ?? "").split(",").map((x) => x.trim().toLowerCase()).includes(email.toLowerCase()); }
export default async function AdminToolsPage() { const session = await getSession(); if (!session || !ok(session.user.email)) return notFound(); const [ops, audit] = await Promise.all([getAdminTools(), listAdminAudit({ limit: 5 })]); const checks = [{ name: "Gateway", state: "Healthy" }, { name: "Database", state: "Unknown" }, { name: "Redis", state: "Unknown" }, { name: "Pricing worker", state: "Unknown" }, { name: "Reconcile worker", state: "Unknown" }, { name: "Deposit monitor", state: "Unknown" }]; return <div className="space-y-6"><div><h1 className="text-2xl font-semibold text-text-primary">Tools</h1><p className="mt-1 text-sm text-text-secondary">System health and treasury operations</p></div><section className="rounded-lg border border-border-default bg-surface p-6"><h2 className="mb-4 font-semibold">System health</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{checks.map((check) => <div key={check.name} className="rounded-md border border-border-subtle bg-surface-2 p-3"><p className="text-xs text-text-muted">{check.name}</p><p className={`mt-1 text-sm ${check.state === "Healthy" ? "text-success" : check.state === "Unavailable" ? "text-error" : "text-warning"}`}>{check.state}</p></div>)}</div><p className="mt-4 text-xs text-text-muted">Unknown means no authoritative heartbeat is stored yet.</p></section><SweepPanel /><section className="rounded-lg border border-border-default bg-surface p-6"><h2 className="mb-4 font-semibold">Recent operational activity</h2>{audit.length === 0 ? <p className="text-sm text-text-muted">Belum ada data yang ditampilkan.</p> : <div className="space-y-2">{audit.map((entry) => <div key={entry.id} className="flex justify-between border-b border-border-subtle pb-2 text-sm"><span>{entry.action}</span><span className="text-xs text-text-muted"><ClientTime utc={entry.createdAt} /> · {entry.status}</span></div>)}</div>}</section><p className="text-xs text-text-muted">{ops.volume7d.length} daily usage buckets available.</p></div>; }
